# Generated by Django 4.1.3 on 2024-09-19 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_driver_rider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="trips_as_rider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
